name: CI
on: [push, pull_request]
jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Set up Go 1.20
        uses: actions/setup-go@v1
        with:
          go-version: 1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Setup influxdb
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          source ./scripts/setup_influxdb.sh
          echo "::set-env name=INFLUXDB_V2_URL::$INFLUXDB_V2_URL"
          echo "::set-env name=INFLUXDB_V2_TOKEN::$INFLUXDB_V2_TOKEN"
          echo "::set-env name=INFLUXDB_V2_BUCKET_ID::$INFLUXDB_V2_BUCKET_ID"
          echo "::set-env name=INFLUXDB_V2_ORG_ID::$INFLUXDB_V2_ORG_ID"
          echo "::set-env name=TF_ACC::1"

      - name: Run unit tests
        run : task test

